language: node_js

node_js:
  - '12.16.2'

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: run-tests
      script:
        - npm run test
        - npm run lint:js
        - npm run lint:css
    - stage: publish
      script:
        - npm run build:atomik
        - npm run build:styles
      deploy:
        provider: npm
        skip_cleanup: true
        email: '$EMAIL_ADDRESS'
        api_key: $NPM_API_KEY
        on:
          tags: true
    - stage: gihub-pages
      script: npm run build:styleguide
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          tags: true
