language: node_js

node_js:
  - '12.16.2'

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    # Runs unit tests and lints JS and CSS
    - stage: run-tests
      script:
        - npm run test
        - npm run lint:js
        - npm run lint:css
    # Builds and publishes Atomik UI Package to npm
    - stage: publish
      if: type != pull_request
      deploy:
        script:
          - npm run build:atomik
          - npm run build:styles
        provider: npm
        skip_cleanup: true
        email: '$EMAIL_ADDRESS'
        api_key: $NPM_API_KEY
        on:
          tags: true
          branch: master
    # Builds and publishes Atomik UI styleguide to GitHub Pages branch
    - stage: gihub-pages
      if: type != pull_request
      deploy:
        script: npm run build:styleguide
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          tags: true
          branch: master
