language: node_js

node_js:
  - '12.16.2'

before_script:
  - yarn install

script:
  - yarn build:styleguide
  - node server.js

jobs:
  include:
    - stage: Test
      script:
        - yarn test:unit
        - yarn test:accessibility
    - stage: Lint
      script:
        - yarn lint:js
        - yarn lint:sass
    - stage: Publish NPM
      script:
        - yarn build:atomik
        - yarn build:styles
      deploy:
        provider: npm
        skip_cleanup: true
        email: '$EMAIL_ADDRESS'
        api_key: $NPM_API_KEY
        on:
          branch: master
          repo: atomikui/atomikui-core
    - stage: GitHub Pages
      script:
        - yarn splash:install
        - yarn build:splash
        - yarn build:styleguide
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master
          repo: atomikui/atomikui-core
