language: node_js

addons:
  chrome: stable

node_js:
  - '12.16.2'

env:
  global:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

before_install: "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=6060 http://localhost &"

before_script:
  - yarn install

script:
  - yarn build:styleguide
  - node server.js

jobs:
  include:
    - stage: Accessibility Tests
      script:
        - yarn test:accessibility
    - stage: Unit Tests
      script:
        - yarn test:unit
    - stage: Linting
      script:
        - yarn lint:js
        - yarn lint:sass
    - stage: Publish NPM
      script:
        - yarn build:atomik
        - yarn build:styles
      deploy:
        provider: npm
        skip_cleanup: true
        email: '$EMAIL_ADDRESS'
        api_key: $NPM_API_KEY
        on:
          branch: master
          repo: atomikui/atomikui-core
    - stage: GitHub Pages
      script:
        - yarn splash:install
        - yarn build:splash
        - yarn build:styleguide
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: build
        on:
          branch: master
          repo: atomikui/atomikui-core
